== Application
plantuml::components.puml[,,format=svg]

== Shared Kernel
plantuml::module-shared.puml[,,format=svg]
include::module-shared.adoc[]

== Analytics
plantuml::module-analytics.puml[,,format=svg]
include::module-analytics.adoc[]

== Audit
plantuml::module-audit.puml[,,format=svg]
include::module-audit.adoc[]

== Files
plantuml::module-files.puml[,,format=svg]
include::module-files.adoc[]

== Identity
plantuml::module-identity.puml[,,format=svg]
include::module-identity.adoc[]

== Localization
plantuml::module-localization.puml[,,format=svg]
include::module-localization.adoc[]

== Scheduler
plantuml::module-scheduler.puml[,,format=svg]
include::module-scheduler.adoc[]

== Settings
plantuml::module-settings.puml[,,format=svg]
include::module-settings.adoc[]

== Notification
plantuml::module-notification.puml[,,format=svg]
include::module-notification.adoc[]

== Organization
plantuml::module-organization.puml[,,format=svg]
include::module-organization.adoc[]

== Search
plantuml::module-search.puml[,,format=svg]
include::module-search.adoc[]

== Webhooks
plantuml::module-webhooks.puml[,,format=svg]
include::module-webhooks.adoc[]

== Document
plantuml::module-document.puml[,,format=svg]
include::module-document.adoc[]

