@startuml
title <size:24>Application</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("Application_boundary", "Application", $tags="") {
  Container_Boundary("Application.Application_boundary", "Application", $tags="") {
    Component(Application.Application.Identity, "Identity", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.IntegrationHub, "Integration Hub", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Localization, "Localization", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Maintenance, "Maintenance", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Scheduler, "Scheduler", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Settings, "Settings", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Subscription, "Subscription", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Exchange, "Exchange", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Payments, "Payments", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Profile, "Profile", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Notification, "Notification", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Organization, "Organization", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.APIKeys, "API Keys", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Billing, "Billing", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Search, "Search", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Signup, "Signup", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Support, "Support", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Document, "Document", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Webhooks, "Webhooks", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.MCP, "MCP", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Access, "Access", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Analytics, "Analytics", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Audit, "Audit", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Compliance, "Compliance", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Files, "Files", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Geolocation, "Geolocation", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(Application.Application.Files, Application.Application.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Scheduler, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Compliance, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Geolocation, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Search, Application.Application.Identity, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Search, Application.Application.Organization, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Search, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Maintenance, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Signup, Application.Application.Organization, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Signup, Application.Application.Notification, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Signup, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.Subscription, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.Organization, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.Notification, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.Subscription, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Billing, Application.Application.Organization, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Support, Application.Application.Notification, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Support, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.Exchange, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.Settings, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.IntegrationHub, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.Identity, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Audit, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Localization, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Exchange, Application.Application.Files, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Exchange, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Exchange, Application.Application.Subscription, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Access, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Payments, Application.Application.IntegrationHub, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Payments, Application.Application.Subscription, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Payments, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Webhooks, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Access, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Maintenance, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Subscription, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Document, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Exchange, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Organization, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Search, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Billing, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.MCP, Application.Application.Support, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Organization, Application.Application.Access, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Organization, Application.Application.Exchange, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Organization, Application.Application.Identity, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Organization, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Organization, Application.Application.Subscription, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Document, Application.Application.Files, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Document, Application.Application.Search, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Document, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Analytics, Application.Application.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Identity, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Subscription, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.IntegrationHub, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.APIKeys, Application.Application.Organization, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.APIKeys, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Profile, Application.Application.SharedKernel, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Profile, Application.Application.Identity, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Profile, Application.Application.Files, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Settings, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.Organization, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.Support, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.Exchange, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.Subscription, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Webhooks, Application.Application.Subscription, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml