@startuml
title <size:24>Notification</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("Application_boundary", "Application", $tags="") {
  Container_Boundary("Application.Application_boundary", "Application", $tags="") {
    Component(Application.Application.IntegrationHub, "Integration Hub", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Settings, "Settings", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Exchange, "Exchange", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Notification, "Notification", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
    Component(Application.Application.Identity, "Identity", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(Application.Application.Notification, Application.Application.Exchange, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.Settings, "listens to", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.IntegrationHub, "depends on", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Notification, Application.Application.Identity, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Identity, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Settings, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.IntegrationHub, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Exchange, Application.Application.SharedKernel, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml