-- Five index corrections in two directions: three go onto purge paths that had nothing at all
-- (§1, §2, §3), and two come off write paths where nothing reads them any more (§4, §5). Same method
-- as V49/V50: every number below is EXPLAIN (ANALYZE, BUFFERS) against a seeded throwaway
-- Postgres 18.4 — the same 5.6M-row database V50's header describes, plus a 500k-row event_inbox
-- seeded for §1 because the shipped one is empty — warm cache, repeated until stable, and quoted next
-- to the statement it justifies.
--
-- BOTH DIRECTIONS ARE THE SAME MISTAKE. V49 and V50 found indexes that do not do the job their name
-- implies; this file finds jobs whose index never existed and indexes whose job stopped existing. What
-- ties all five together is that NOT ONE of them can be settled by reading the schema — an index's
-- worth is a fact about the statements that run against it, not about the columns it covers. So each
-- section names the statement, and §6 records the two proposals that did NOT survive being measured,
-- because the next audit will re-propose both from the schema alone.
--
-- PLAIN `create index` / `drop index`, NOT `concurrently`. V50's header derives this at length and
-- AGENTS §4.6 now carries it: a `-- flyway:executeInTransaction=false` comment is INERT on
-- flyway-core 12.4.0 (script metadata comes only from a sidecar `V<n>__<name>.sql.conf`), so the
-- transaction would stay and every CONCURRENTLY statement would abort at context startup. This whole
-- file applied to the seeded database, inside one transaction as Flyway runs it, in 330 ms: 161 ms
-- the event_inbox build over 500k rows, 24 ms the idempotency_key build over 100k, 3.5 ms org_group,
-- both removals under a millisecond, and 140 ms the COMMIT itself flushing the new index files.
-- Revisit when a table here grows by an order of magnitude; the sidecar is the mechanism that
-- actually works.

-- ---------------------------------------------------------------------------------------------
-- 1. event_inbox.processed_at — the nightly purge batches, and batching WITHOUT an index on the
--    ordering column is not a fix, it is a multiplier.
-- ---------------------------------------------------------------------------------------------

-- EventInbox.purgeProcessedBatch issues, up to MAX_BATCHES = 100 times per nightly run:
--     delete from event_inbox where (listener_id, message_id) in (
--         select listener_id, message_id from event_inbox
--         where processed_at < ? order by processed_at limit 1000)
-- The outer delete was never the problem — it drives event_inbox_pkey from whatever the sub-select
-- returns, 1000 lookups, bounded. The sub-select was, and the `order by` is what made it unbounded:
-- with nothing on processed_at, "the thousand oldest" can only be found by reading EVERY row past the
-- cutoff and top-N sorting it. Measured on 500k rows with 267k past a 14-day cutoff:
--     Seq Scan (266987 rows) -> top-N heapsort -> Limit    5682 buffers, 47.1 ms   (scan node)
--     whole statement                                     11682 buffers, 61.9 ms   (133 ms cold)
-- With the index the scan IS the order, so LIMIT 1000 stops it at 1000 rows instead of end-of-table:
--     Index Scan (1000 rows) -> Limit                       1005 buffers,  0.29 ms  (scan node)
--     whole statement                                       7005 buffers, 15.6 ms
-- 5.7x fewer buffers on the statement, 160x on the part the index touches. Per batch — so at this
-- backlog the run's 100 batches go from ~6.2 s of scanning to ~1.6 s, and the gap widens with the
-- table because the old shape is O(rows past cutoff) per batch while the new one is O(1000).
--
-- The trap the numbers hide: deleting 1000 rows per batch barely shrinks the next batch's scan, so a
-- purge that falls behind gets SLOWER per row purged, not faster. That is the failure mode this
-- prevents, and it is invisible until the backlog is large enough to matter.
create index idx_event_inbox_processed on event_inbox (processed_at);

-- ---------------------------------------------------------------------------------------------
-- 2. idempotency_key.created_at — the same shape one table over, and READ §2's second half BEFORE
--    deciding this index is unused. It is worthless against the statement that stood here
--    yesterday, and necessary against the one that stands here now.
-- ---------------------------------------------------------------------------------------------

-- IdempotencyStore.purgeBatch is now the inbox's shape: `... in (select principal, idem_key from
-- idempotency_key where created_at < ? order by created_at limit 1000)`, up to 100 batches a night.
-- Measured on a 100k-row clone (41 MB heap, created_at correlated 1.000 as it is in life — rows are
-- appended in time order — and 50% of the table past the cutoff, which is the steady state the
-- defaults produce; see below):
--     Seq Scan (50006 rows) -> top-N heapsort -> Limit    5264 buffers,  9.3 ms   (scan node)
--     whole statement                                    10264 buffers, 16.1 ms   (23.1 ms cold)
--     Index Scan (1000 rows) -> Limit                       57 buffers,  0.11 ms  (scan node)
--     whole statement                                     5057 buffers,  2.37 ms
-- 92x on the scan node's buffers, 6.8x on the statement, per batch.
--
-- NOW THE PART THAT MATTERS TO WHOEVER AUDITS THIS NEXT. Until this run, the purge was ONE unbatched
-- `delete from idempotency_key where created_at < ?`, and against THAT statement this index is worth
-- exactly nothing — not "a little", nothing, and it was measured rather than assumed. Retention
-- defaults to 1 day and the job runs nightly, so at each run the table holds roughly two windows and
-- the sweep takes the older half: ~50% selectivity, at which Postgres picks a Seq Scan with the index
-- sitting right there. Pushing selectivity down to 12.5% (a 7-day retention) and then to 1% did not
-- change the plan, and neither did rebuilding created_at to a 0.9996 correlation. A bare range
-- predicate over a large fraction of a table is a sequential scan and no index changes that.
--
-- What changed is not the data, the size or the selectivity — it is the ORDER BY … LIMIT. That is
-- what turns "half the table" into "the thousand oldest", and an ordered read of a thousand rows is
-- the one shape a btree wins outright. So: this index is load-bearing for the batched purge and
-- DEAD WEIGHT for the unbatched one. If a future change ever un-batches it, drop this index in the
-- same commit — and if it stays batched, do not drop this index because the old statement's numbers
-- said it did nothing.
create index idx_idempotency_key_created on idempotency_key (created_at);

-- ---------------------------------------------------------------------------------------------
-- 3. A TOTAL index for an FK cascade check — V50 §3's rule, applied to the one child of org_role
--    that had nothing. THE `where deleted_at is null` PREDICATE IS DELIBERATELY ABSENT AND MUST STAY
--    ABSENT: Postgres cannot use a PARTIAL index to satisfy a referential-integrity check, because
--    the RI probe is a bare equality on the key with no `deleted_at` qual for the planner to match
--    the predicate against.
-- ---------------------------------------------------------------------------------------------

-- org_role has three children — membership.role_id, org_group.role_id, role_permission.role_id — and
-- the first and third were already covered (idx_membership_role from V11; role_permission's own
-- primary key leads with role_id). org_group had nothing at all, which makes the other two a control
-- group inside the very same statement. SoftDeletePurgeJob's actual org_role batch, 500 rows:
--     before   org_group_role_id_fkey  66.8 / 70.8 ms     Execution Time 79.9 / 78.6 ms
--              membership_role_id_fkey  6.5 /  5.3 ms  |  role_permission  4.4 / 0.9 ms   (controls)
--     after    org_group_role_id_fkey   6.8 ms            Execution Time 16.5 ms
--              membership_role_id_fkey  6.8 ms         |  role_permission  1.3 ms
-- 10x on the trigger, 4.8x on the batch, and the shape of the before-picture is the tell: ONE of
-- three identical-looking FK checks costing 84-90% of the statement.
--
-- org_group holds 5000 rows today, so read the ratio, not the milliseconds — the ratio is
-- (roles purged x rows in org_group) and only one of those two numbers ever shrinks.
--
-- THIS INDEX HAS NO QUERY READER, AND THAT IS NOT A DEFECT — it is the point, and it is what will
-- make it look deletable. Nothing in the application filters org_group by role_id: OrgGroupRepository
-- declares `existsByRoleId`, but NOTHING CALLS IT (RoleService guards role deletion on
-- MembershipRepository.existsByRoleId — a different repository on a different table), so even that
-- would-be reader issues no SQL. The only caller is Postgres's own RI trigger. An audit conducted the
-- way V49 was conducted — "name the query this index serves" — finds nothing here and concludes dead
-- weight; pg_stat_user_indexes is not the tiebreaker either, because RI probes only run when the
-- nightly purge runs, so a freshly restored environment shows a perfectly credible idx_scan = 0. The
-- `_fk` suffix is the load-bearing part of the name, exactly as in V50 §3.
create index idx_org_group_role_fk on org_group (role_id);

-- ---------------------------------------------------------------------------------------------
-- 4. idx_person_name — 10 MB serving nothing, and the interesting cost is not the 10 MB.
-- ---------------------------------------------------------------------------------------------

-- V10 created it to sort the person listing by display name. That listing never shipped that way:
-- PersonAccessService.LIST_SORT is (created_at desc, id desc) and lands on idx_person_recent, and
-- nothing anywhere filters, sorts or joins on formatted_name. Checked rather than assumed, because
-- this run ADDS a name API — GET/PATCH /admin/users/{id}(/name) and PATCH /me/name — and a name
-- SEARCH would have kept the index. It reads and writes the column and projects it into the payload;
-- it never looks a person up by it. The admin search projection indexes e-mail only
-- (SearchEventListeners writes `event.email()` as both the title and the body of a `user` row), so
-- that is not a hidden reader either. pg_stat_user_indexes agrees: 0 scans against 57 on
-- idx_person_recent and 2.49M on person_pkey. The one plan that uses it is an equality on
-- formatted_name, which no code issues.
--
-- The storage is 10 MB against a 26 MB heap. The reason to act on it is the write path, and the
-- mechanism is worth stating because dropping ONE index here removes the maintenance of FOUR:
-- an UPDATE can be HOT (heap-only, no index touched at all) only when no INDEXED column changes.
-- With this index, `update person set formatted_name = ?, updated_at = ?` — the name PATCH's entire
-- statement — changes an indexed column, so it is never HOT and must post new entries into
-- person_pkey, idx_person_recent, idx_person_scan and this one. Without it, formatted_name is
-- indexed by nothing, updated_at is indexed by nothing, and the same statement touches no index.
-- Over 2000 single-row name PATCHes, alternating arms on disjoint row ranges, each arm starting from
-- a CHECKPOINT:
--     HOT updates    0 / 2000  ->  1678 / 2000
--     WAL per update 570 / 582 / 577 / 592 bytes  ->  277 / 280 / 273 bytes    (~52%)
-- full_page_writes was off FOR THE MEASUREMENT ONLY, for the reason V50 §4 records: an FPI is 8 kB
-- against a ~130-byte row, so with it on the result turns on whether a checkpoint lands mid-run. 52%
-- is the intrinsic figure; in production FPIs dilute the share.
drop index idx_person_name;

-- ---------------------------------------------------------------------------------------------
-- 5. payment.merchant_reference's UNIQUE — a uniqueness guarantee the primary key already gives,
--    bought a second time for 11 MB. AND: THE SEEDED DATA DOES NOT SHOW THIS. Read on.
-- ---------------------------------------------------------------------------------------------

-- Payment.java line 92 is the only assignment to the field in the codebase — there is no setter and
-- no second writer:
--     payment.merchantReference = payment.id.toString();
-- V40's own header says the same in prose ("our payment id stringified"). So the column is a
-- lossless function of the primary key, and payment_pkey already makes it unique; the UNIQUE
-- constraint can only ever reject a row payment_pkey would have rejected first.
--
-- THE HONEST CAVEAT, stated rather than buried: the review database does NOT reproduce that
-- derivation. Its payments carry synthetic references ('ref-1', 'ref-2', …) and 0 of 200000 rows
-- satisfy `merchant_reference = id::text`. So this drop rests on the code — one assignment site,
-- grepped — and NOT on the data, and anyone re-checking it against the seed will find the claim
-- looking false. Check Payment.initiate, not a `select`.
--
-- Nothing reads the column either. The Pesapal IPN and browser callback both resolve by
-- gateway_reference (PaymentService.refreshByGatewayReference, served by idx_payment_gateway_ref);
-- the OrderMerchantReference parameter is echoed straight back into the acknowledgment body and never
-- used for a lookup. pg_stat_user_indexes: 0 scans.
--
-- Worth 11 MB against a 31 MB heap, plus a probe-and-insert into a 36-character key on every payment
-- initiation. WAL per payment insert, three alternating pairs of 5000 inserts, full_page_writes off:
--     571.0 / 565.1 / 567.3 bytes  ->  429.5 / 430.2 / 426.6 bytes    (24.5%)
--
-- `alter table … drop constraint`, not `drop index`: V40 declared it inline as `varchar(50) not null
-- unique`, so payment_merchant_reference_key is a CONSTRAINT with an index under it, and `drop index`
-- on it fails. `not null` stays — the column is still written and still returned.
alter table payment drop constraint payment_merchant_reference_key;

-- ---------------------------------------------------------------------------------------------
-- 6. NOT DONE, and recorded so the next audit does not spend the afternoon rediscovering them. Both
--    were proposed on the schema, and the schema was not wrong about either — it was just not the
--    whole question.
-- ---------------------------------------------------------------------------------------------

-- (a) idx_translation_locale on translation (locale) where deleted_at is null. KEPT.
--     It is exactly what it was called: a strict column prefix of uq_translation_locale_key
--     (locale, msg_key) carrying an identical partial predicate, so the wider index can ANSWER
--     everything the narrower one answers. Answering is not the test. TranslationRepository
--     .findByLocale is a live reader — the whole-bundle load behind every TranslationBundles cache
--     miss — and TranslationService.list filters on the same column. Measured, one locale of 5000
--     keys:
--         idx_translation_locale       229 buffers, 0.31-0.41 ms
--         uq_translation_locale_key   1144 buffers, 0.40-0.42 ms
--     5x the buffers, and the cause is ORDER, not width: a btree stores equal keys in TID order, so
--     scanning (locale) walks the heap forwards and touches each of the 224 heap pages about once,
--     while scanning (locale, msg_key) returns rows in msg_key order — uncorrelated with the heap —
--     and touches a page per row. The gap therefore grows with the number of keys in a locale, and
--     the wall-clock tie here only holds because the whole table is 1.8 MB and entirely cached. For
--     144 kB, on a table admins write to by hand, there is nothing to win.
--
-- (b) Plain document(org_id) and ticket(org_id). NOT ADDED — the query was fixed instead, in this
--     same run, which is the right end of the problem. OrgExportService's extracts used to read
--     `select * from <t> where org_id = ? limit 1000` with no `deleted_at is null`, and a partial
--     index is invisible to a query that does not prove its predicate, so both fell to parallel seq
--     scans. They now carry the predicate (and an explicit ORDER BY, for reproducibility of a legal
--     artifact) and land on the indexes V23/V36 already built:
--         document   Parallel Seq Scan 3964 buffers, 28.1 ms  ->  idx_document_org_recent  5 buffers, 0.60 ms
--         ticket     Parallel Seq Scan 4251 buffers, 31.0 ms  ->  idx_ticket_org           4 buffers, 0.73 ms
--     Two plain indexes here would have cost ~22 MB to make a wrong query fast, and would then have
--     had to be dropped again once the query was written properly. An index is not the remedy for a
--     predicate somebody forgot.
